### ISSUE TITLE
Problem with Kivy Portable Package Installation on Windows

### ISSUE THREAD

**Issue by lysigk** [kivy/kivent#89] opened 2015-08-14 19:02 UTC
When trying to run `python setup.py build_ext install` according to the instructions in the readme I get the following error message: `AttributeError: 'module' object has no attribute 'get_includes'`. 

I'm quite new to Python and can't really figure out how to solve this problem. Would really appreciate your help!

Oh, and I'm using Python & Kivy 3.4 on Windows 10.

**Comment by Kovak** [comment] 2015-08-14 19:04
Hi,

You need to update your Kivy to master branch. Follow the instructions in this section http://kivy.org/docs/installation/installation-windows.html#use-development-kivy

**Comment by lysigk** [comment] 2015-08-14 19:30
Ok, updating Kivy worked so far. But now I get the error `ImportError: No module named 'kivy'`. Same thing happens when I try to run one of the examples (which worked before updating).

**Comment by Kovak** [comment] 2015-08-14 20:02
Did you name the new Kivy directory 'kivy' or 'kivy34', I believe the kivy.bat searches inside the 'kivy34' path?

**Comment by lysigk** [comment] 2015-08-14 20:48
Alrigth, renaming to 'kivy34' solved the problem. But when I try to run the examples mentioned in the installation instructions there is the error message `ImportError: No module named 'cPickle'`.

**Comment by Kovak** [comment] 2015-08-14 21:35
This should be fixed in #90 , will you try the fix_cpickle_import branch and see if it solves your issue.

**Comment by lysigk** [comment] 2015-08-15 10:06
The cPickle issue seems to be solved with the changes in the fix_cpickle_import branch, thanks!

So now I get  `TypeError: object.__init__() takes no parameters`.

**Comment by Kovak** [comment] 2015-08-15 10:15
Can you post the full traceback for the new error?

**Comment by lysigk** [comment] 2015-08-15 10:33
Oh, of course:

`Traceback (most recent call last):
   File "main.py", line 81, in <module>
     YourAppNameApp().run()
   File "D:\Kivy\kivy34\kivy\app.py", line 798, in run
     self.load_kv(filename=self.kv_file)
   File "D:\Kivy\kivy34\kivy\app.py", line 595, in load_kv
     root = Builder.load_file(rfilename)
   File "D:\Kivy\kivy34\kivy\lang.py", line 1801, in load_file
     return self.load_string(data, **kwargs)
   File "D:\Kivy\kivy34\kivy\lang.py", line 1879, in load_string
     widget = Factory.get(parser.root.name)()
   File "main.py", line 20, in __init__
     super(TestGame, self).__init__(**kwargs)
   File "D:\Kivy\kivy34\kivy\uix\widget.py", line 322, in __init__
     Builder.apply(self)
   File "D:\Kivy\kivy34\kivy\lang.py", line 1924, in apply
     self._apply_rule(widget, rule, rule)
   File "D:\Kivy\kivy34\kivy\lang.py", line 2038, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "D:\Kivy\kivy34\kivy\lang.py", line 2035, in _apply_rule
     child = cls(__no_builder=True)
   File "kivent_core\systems\gamesystem.pyx", line 121, in kivent_core.systems.g
amesystem.GameSystem.__init__ (kivent_core/systems/gamesystem.c:2038)
   File "kivent_core\uix\cwidget.pyx", line 89, in kivent_core.uix.cwidget.CWidg
et.__init__ (kivent_core/uix/cwidget.c:2009)
   File "kivy\_event.pyx", line 253, in kivy._event.EventDispatcher.__init__ (ki
vy\_event.c:4863)
 TypeError: object.__init__() takes no parameters`

**Comment by haskjold** [comment] 2015-09-05 16:47
Hi

I'm seeing the same error on Linux. Kivy, Cymunk and Kivent built from master branches (with the cpickle fix cherry-picked), when trying to run examples 2 - 8.

```bash
...
File "kivent_core/systems/gamesystem.pyx", line 121, in kivent_core.systems.gamesystem.GameSystem.__init__ (kivent_core/systems/gamesystem.c:2033)
File "kivent_core/uix/cwidget.pyx", line 89, in kivent_core.uix.cwidget.CWidget.__init__ (kivent_core/uix/cwidget.c:2004)
File "kivy/_event.pyx", line 253, in kivy._event.EventDispatcher.__init__ (kivy/_event.c:4863)
TypeError: object.__init__() takes no parameters
```

**Comment by Kovak** [comment] 2015-09-12 18:40
This is an issue in Kivy not KivEnt. Try again with the most recent master and if it still occurs let me know.

**Comment by haskjold** [comment] 2015-09-16 20:58
Tested again with Kivy master 0ca33cfb2d74cb5f5047ff6d49315023880ed1a5, still seeing the same errors.

**Comment by bionoid** [comment] 2015-09-16 21:13
Probably caused by passing a non-property kwarg to ``EventDispatcher.__init__()``, this used to work, but was recently changed in kivy master

```python
from kivy.event import EventDispatcher
EventDispatcher(not_a_property=1)
```

```
 Traceback (most recent call last):
   File "test.py", line 2, in <module>
     EventDispatcher(not_a_property=1)
   File "kivy/_event.pyx", line 253, in kivy._event.EventDispatcher.__init__ (kivy/_event.c:4863)
 TypeError: object.__init__() takes no parameters
```

**Comment by Kovak** [comment] 2015-09-16 21:30
This should be fixed with 
https://github.com/kivy/kivent/tree/fix_cwidget_kwargs

**Comment by haskjold** [comment] 2015-09-17 05:47
Yeah, examples work with fix_cwidget_kwargs branch.

**Closed** 2015-10-14 00:48 UTC
